"""
data/generate_seed.py

Baca leads_seed.csv -> normalize tiap row pakai app.services.normalization
-> tulis jadi leads_seed.sql (CREATE TABLE + INSERT) yang sudah bersih.

File .sql hasilnya dipakai oleh docker-entrypoint-initdb.d/ saat container
Postgres pertama kali start, jadi data seed sudah normalized SEBELUM masuk DB.

Jalankan di luar Docker (di mesin kamu), sebelum build image.
Bisa dijalankan dari mana saja (root backend/ maupun dari dalam data/),
karena path CSV/SQL di-resolve relatif terhadap lokasi file ini:

    python data/generate_seed.py leads_seed.csv leads_seed.sql
    # atau, dari dalam folder data/:
    python generate_seed.py leads_seed.csv leads_seed.sql
"""

import csv
import sys
from pathlib import Path

# File ini ada di backend/data/generate_seed.py
# app/services/normalization.py ada di backend/app/services/
# Jadi harus naik satu level (dari data/ ke backend/) supaya `app` bisa di-import
BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.services.normalization import normalize_lead  # noqa: E402


TABLE_NAME = "leads"

# Urutan kolom di tabel `leads` (harus konsisten dengan CREATE TABLE)
COLUMNS = [
    "record_id",
    "name",
    "job_title",
    "company_name",
    "email",
    "phone_number",
    "country_region",
    "city",
    "lead_status",
    "lifecycle_stage",
    "original_source",
    "original_source_drill_down_1",
    "contact_owner",
    "create_date",
    "last_modified_date",
    "notes",
    "annual_revenue",
    "marketing_contact_status",
    "gdpr_consent",
    "lead_score",
]

# Mapping header CSV asli -> nama kolom snake_case
CSV_HEADER_MAP = {
    "Record ID": "record_id",
    "First Name": "first_name",
    "Last Name": "last_name",
    "Full Name": "full_name",
    "Job Title": "job_title",
    "Company Name": "company_name",
    "Email": "email",
    "Phone Number": "phone_number",
    "Country/Region": "country_region",
    "City": "city",
    "Lead Status": "lead_status",
    "Lifecycle Stage": "lifecycle_stage",
    "Original Source": "original_source",
    "Original Source Drill-Down 1": "original_source_drill_down_1",
    "Contact Owner": "contact_owner",
    "Create Date": "create_date",
    "Last Modified Date": "last_modified_date",
    "Notes": "notes",
    "Annual Revenue": "annual_revenue",
    "Marketing contact status": "marketing_contact_status",
    "GDPR consent": "gdpr_consent",
    "Lead Score": "lead_score",
}


def sql_escape(value) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


CREATE_TABLE_SQL = f"""CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
    record_id TEXT PRIMARY KEY,
    name TEXT,
    job_title TEXT,
    company_name TEXT,
    email TEXT,
    phone_number TEXT,
    country_region TEXT,
    city TEXT,
    lead_status TEXT,
    lifecycle_stage TEXT,
    original_source TEXT,
    original_source_drill_down_1 TEXT,
    contact_owner TEXT,
    create_date DATE,
    last_modified_date DATE,
    notes TEXT,
    annual_revenue NUMERIC,
    marketing_contact_status TEXT,
    gdpr_consent BOOLEAN,
    lead_score NUMERIC
);"""


def convert(input_csv: str, output_sql: str) -> None:
    with open(input_csv, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        raw_rows = list(reader)

    insert_statements = []

    for raw_row in raw_rows:
        # Ubah key header CSV asli -> snake_case
        row = {CSV_HEADER_MAP[k]: v for k, v in raw_row.items() if k in CSV_HEADER_MAP}

        # Normalize pakai fungsi yang sama dengan ingest endpoint
        cleaned = normalize_lead(row)

        values = ", ".join(sql_escape(cleaned.get(col)) for col in COLUMNS)
        col_list = ", ".join(COLUMNS)
        insert_statements.append(f"INSERT INTO {TABLE_NAME} ({col_list}) VALUES ({values});")

    with open(output_sql, "w", encoding="utf-8") as out:
        out.write("-- Auto-generated by scripts/generate_seed.py\n")
        out.write("-- Data sudah dinormalize memakai app.services.normalization\n\n")
        out.write(CREATE_TABLE_SQL + "\n\n")
        out.write("\n".join(insert_statements) + "\n")

    print(f"Done. {len(raw_rows)} rows -> {output_sql} (normalized)")


def resolve_path(path_str: str) -> str:
    """
    Kalau path yang dikasih relatif dan file-nya nggak ketemu dari current
    working directory, coba cari relatif terhadap folder script ini (data/).
    Jadi script tetap jalan baik dipanggil dari backend/ maupun dari data/.
    """
    p = Path(path_str)
    if p.is_absolute() or p.exists():
        return str(p)
    fallback = Path(__file__).resolve().parent / path_str
    return str(fallback)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python data/generate_seed.py <input_csv> <output_sql>")
        sys.exit(1)

    input_path = resolve_path(sys.argv[1])
    output_path = resolve_path(sys.argv[2])

    convert(input_path, output_path)